[package]
name = "nez"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
rayon = "1.10.0"
zarrs = { version = "0.21", default-features = false, features = [
    "filesystem",
] }
